#!/usr/bin/env python3
"""
초기 설정 스크립트
"""
import os
import secrets
from pathlib import Path
from mnemonic import Mnemonic
from tronpy.keys import PrivateKey


def main():
    print("=" * 60)
    print("  TRON USDT Gateway - 초기 설정")
    print("=" * 60 + "\n")
    
    # 1. 니모닉 설정
    print("1️⃣ 마스터 니모닉 설정")
    print("   모든 사용자 주소가 이 니모닉에서 파생됩니다.\n")
    
    mnemo = Mnemonic("english")
    
    use_existing = input("기존 니모닉이 있습니까? (y/n): ").strip().lower()
    
    if use_existing == 'y':
        mnemonic = input("24단어 니모닉 입력: ").strip()
        if not mnemo.check(mnemonic):
            print("❌ 유효하지 않은 니모닉입니다!")
            return
    else:
        mnemonic = mnemo.generate(strength=256)
        print("\n🔐 새 니모닉 생성됨:")
        print("=" * 60)
        print(mnemonic)
        print("=" * 60)
        print("\n⚠️  중요: 이 니모닉을 안전하게 백업하세요!")
        print("   이것이 모든 사용자 자금을 복구하는 유일한 방법입니다.\n")
        input("백업 완료 후 Enter를 누르세요...")
    
    # 2. 메인 핫월렛 설정
    print("\n2️⃣ 메인 핫월렛 설정")
    print("   수집된 자금을 보관하고 출금을 처리합니다.\n")
    
    create_new = input("새 메인 지갑을 생성하시겠습니까? (y/n): ").strip().lower()
    
    if create_new == 'y':
        private_key = PrivateKey.random()
        main_address = private_key.public_key.to_base58check_address()
        main_private_key = private_key.hex()
        
        print(f"\n📦 메인 지갑 생성됨:")
        print(f"   주소: {main_address}")
        print(f"   개인키: {main_private_key}")
        print("\n⚠️  개인키를 안전하게 보관하세요!")
    else:
        main_address = input("메인 지갑 주소: ").strip()
        main_private_key = input("메인 지갑 개인키: ").strip()
    
    # 3. TronGrid API 키
    print("\n3️⃣ TronGrid API 키 설정")
    print("   https://www.trongrid.io 에서 발급 (무료 3개)")
    
    api_key_1 = input("API Key 1 (필수): ").strip()
    api_key_2 = input("API Key 2 (선택, Enter로 건너뛰기): ").strip()
    api_key_3 = input("API Key 3 (선택, Enter로 건너뛰기): ").strip()
    
    # 4. API 시크릿 키
    print("\n4️⃣ API 시크릿 키")
    api_secret = input("API 시크릿 (Enter로 자동 생성): ").strip()
    if not api_secret:
        api_secret = secrets.token_hex(32)
        print(f"   생성됨: {api_secret}")
    
    # 5. Telegram 알림 (선택)
    print("\n5️⃣ Telegram 알림 (선택)")
    telegram_token = input("Bot Token (Enter로 건너뛰기): ").strip()
    telegram_chat_id = input("Chat ID (Enter로 건너뛰기): ").strip()
    
    # 6. .env 파일 생성
    print("\n6️⃣ .env 파일 생성 중...")
    
    env_content = f"""# TRON USDT Gateway Configuration
# Generated by setup script

# ============ 마스터 시드 ============
MASTER_MNEMONIC={mnemonic}

# ============ 메인 핫월렛 ============
MAIN_WALLET_ADDRESS={main_address}
MAIN_WALLET_PRIVATE_KEY={main_private_key}

# ============ TronGrid API ============
TRONGRID_API_URL=https://api.trongrid.io
TRONGRID_API_KEY_1={api_key_1}
TRONGRID_API_KEY_2={api_key_2}
TRONGRID_API_KEY_3={api_key_3}

# ============ USDT 컨트랙트 ============
USDT_CONTRACT=TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t

# ============ 데이터베이스 ============
DATABASE_URL=sqlite+aiosqlite:///./data/gateway.db

# ============ 서버 설정 ============
HOST=0.0.0.0
PORT=8000
API_SECRET_KEY={api_secret}

# ============ 스위핑 설정 ============
SWEEP_THRESHOLD_USDT=10
POLLING_INTERVAL_SECONDS=300
REQUIRED_CONFIRMATIONS=25

# ============ 에너지 설정 ============
ENERGY_PER_TRANSFER=65000
USE_STAKING=false
USE_ENERGY_RENTAL=true

# ============ 출금 설정 ============
MAX_DAILY_WITHDRAWAL=10000
MAX_SINGLE_WITHDRAWAL=5000

# ============ 알림 설정 ============
TELEGRAM_BOT_TOKEN={telegram_token}
TELEGRAM_CHAT_ID={telegram_chat_id}
ALERT_LOW_BALANCE_THRESHOLD=1000
ALERT_LARGE_WITHDRAWAL_THRESHOLD=500
"""
    
    env_path = Path(__file__).parent.parent / ".env"
    env_path.write_text(env_content)
    
    # 데이터 디렉토리 생성
    data_dir = Path(__file__).parent.parent / "data"
    data_dir.mkdir(exist_ok=True)
    
    print("\n✅ 설정 완료!")
    print("=" * 60)
    print("  다음 단계:")
    print("=" * 60)
    print("1. pip install -r requirements.txt")
    print("2. 메인 지갑에 TRX 충전 (수수료용)")
    print("3. python -m app.main")
    print("=" * 60)
    print(f"\n🔑 API Key: {api_secret}")
    print(f"📡 API URL: http://localhost:8000")
    print(f"📚 API Docs: http://localhost:8000/docs\n")


if __name__ == "__main__":
    main()
